### ISSUE TITLE
give application error after deploy on my dyno

### ISSUE THREAD

**Issue by pushhub** [Mrwerdo/DeployToHeroku#2]
Hi Andrew,
I recived application error after deploy on my dyno & my dyno log is :
https://gist.github.com/pushhub/7ebab6f1454490d3c59bcfb0b94d5446
waiting for your response
finest regards
goodbye

**Comment by Mrwerdo** [comment]
Hi pushhub, looks like the you're not using the latest version. In fact, v0.0.1 doesn't do anything at all! I'd recommend using v0.0.5 at the moment if you're justing looking for a GitHub Action to deploy a zip file to Heroku.

**Comment by pushhub** [comment]
hello again ,
at the first fine thanks for fast response ,
please give the typescript heroku buildpack is worked fine with your code ,
waiting for your response
finest regards
goodbye

**Comment by Mrwerdo** [comment]
Sorry, I don't understand what you're trying to say. You do know this is a [Github Action](https://help.github.com/en/actions/getting-started-with-github-actions/overview), right?

What were the steps you took to produce the problem?
